# Welcome to Jekyll!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ezio's Blog
email: ezio_zhang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Self study 	: AOSP , Python , 
  Worked with 	: uboot , linux , RTOS ,
  Using now 	: PowerPC , ARM
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oska874
github_username:  oska874

# Build settings
markdown: kramdown

kramdown:
  input: GFM

timezone: UTC+8
encoding: utf-8

