# Welcome to Jekyll!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ezio's Notes
email: ezio_zhang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  AOSP , Python , uboot , linux , RTOS , lwip , AMP , PowerPC , ARM
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oska874
github_username:  oska874

# Build settings


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
     - fenced_code_blocks
     - no_intra_emphasis
     - strikethrough
     - autolink
     - tables

#markdown: kramdown

#kramdown:
#  input: GFM
#  auto_ids:      true
#  auto_id_prefix: 'id-'

encoding: utf-8

excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: "_posts/"
    values:
      layout: "post" 
